name: sign

on:
  # schedule:
  #   - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  sign:
    name: sign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Build Packages And Sign
        run: |
          pnpm install
          pnpm sign
        env:
          BDUSS: ${{ secrets.BDUSS }}
