name: publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  sign:
    name: sign
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Build Packages And Sign
        run: |
          pnpm install
          pnpm sign
